plugins {
    id 'java'
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = 'https://maven.northconcepts.com/public/repositories/datapipeline'
    }
}

sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21
version = '11.0.0'

configurations.all {
    // Check for updates every 30 minutes (0 for every build)
    //resolutionStrategy.cacheChangingModulesFor 30, 'minutes'
    //resolutionStrategy.cacheChangingModulesFor 0, 'minutes'
}

dependencies {
    implementation "com.northconcepts:northconcepts-datapipeline-small-business:${version}"
    implementation "com.northconcepts:northconcepts-datapipeline-foundations:${version}"
    implementation "com.northconcepts:northconcepts-datapipeline-integrations-parquet:${version}"
    implementation 'junit:junit:4.13.2'
    implementation 'org.hsqldb:hsqldb:2.4.0'
    implementation 'com.h2database:h2:1.4.200'
}
