plugins {
    id 'java'
    id 'war'
    id 'org.gretty' version '4.1.10'
}

sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21

dependencies {
    providedCompile 'jakarta.servlet:jakarta.servlet-api:5.0.0'

    implementation "com.northconcepts:northconcepts-datapipeline-small-business:11.0.0"

    implementation 'org.hsqldb:hsqldb:2.7.4'
    implementation 'org.jboss.resteasy:resteasy-core:6.2.19.Final'

    implementation 'org.apache.commons:commons-fileupload2-jakarta-servlet5:2.0.0-M5'

    //testImplementation 'junit:junit:4.13.2'
}

repositories {
    mavenCentral()
    maven {
        url = 'https://maven.northconcepts.com/public/repositories/datapipeline'
    }
}


base {
    archivesName = 'events2'
}

gretty {
    servletContainer = 'jetty11'

//    httpEnabled = true
//    httpPort = 8081
    contextPath = '/events2'
//    jvmArgs { '-ea' }

//    loggingLevel = 'ALL' // options:   'ALL', 'DEBUG', 'ERROR', 'INFO', 'OFF', 'TRACE', 'WARN'
}
