name: Java CI

on:
  push:
  schedule:
    - cron: '30 13 15 * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file ./DataPipeline-Demo-Build-with-Maven/pom.xml
